DROP TABLE IF EXISTS ROLE CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS BLOCKED_USERS CASCADE;

CREATE TABLE ROLE(
    id bigint generated by default as identity,
    type varchar(20) NOT NULL UNIQUE,
    primary key(id)
);

CREATE TABLE USERS(
    id bigint generated by default as identity,
    account varchar(30) NOT NULL UNIQUE,
    hashed_password varchar(80) NOT NULL,
    nickname varchar(30) NOT NULL UNIQUE,
    email varchar(50) NOT NULL UNIQUE,
    role_id bigint NOT NULL,
    created_at varchar(50) NOT NULL,
    updated_at varchar(50) NOT NULL,
    FOREIGN KEY(role_id) REFERENCES ROLE(id) ON DELETE CASCADE ON UPDATE CASCADE,
    primary key(id)
);

CREATE TABLE USERS_BAN_INFO(
    id bigint generated by default as identity,
    user_id bigint NOT NULL,
    description varchar(300) NOT NULL,
    created_at varchar(50) NOT NULL,
    FOREIGN KEY(user_id) REFERENCES USERS ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(id)
);

INSERT INTO ROLE (type) VALUES ('ALL');
INSERT INTO ROLE (type) VALUES ('ADMIN');
INSERT INTO ROLE (type) VALUES ('MANAGER');
INSERT INTO ROLE (type) VALUES ('USER');
INSERT INTO ROLE (type) VALUES ('BANNED');

--INSERT INTO USERS (account, hashed_password, nickname, email, role_id, created_at, updated_at) VALUES ('test', 'qwer1234', 'test', 'test@test.com', 2, '2022', '2022');
